// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView, HorizontalBox, VerticalBox, GridBox } from "std-widgets.slint";

export struct FileItem := {
    filename: string,
}

FileLine := Rectangle {
    height: 18px;
    property <string> filename;
    
    Rectangle {
        background: touch.has-hover ? #f2f1f8 : white;
        height: 17px;
        animate background { duration: 50ms; easing: ease-in-out; }
    }
    HorizontalLayout {
        t_filename := Text {
            text: root.filename;
        }
    }
    Rectangle { 
        y: 16px;
        height: 1px;
        background: #cccccc;
    }
    touch := TouchArea {
    }
}

MainWindow := Window {
    preferred-width: 400px;
    preferred-height: 600px;

    property <[FileItem]> file-model: [
    ];

    VerticalBox {
        list-view := ListView {
            for file in file-model:  FileLine {
                filename: file.filename;
            }
        }
    }
}
